services:
  express-actuatorjs-db:
    image: postgres:16-alpine
    container_name: express-actuatorjs-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  express-actuatorjs-app:
    image: express-actuatorjs-app
    container_name: express-actuatorjs-app
    build:
      context: .
      dockerfile: Containerfile
    environment:
      DB_HOST: express-actuatorjs-db
    ports:
      - "3000:3000"
